import Header from "./Header"

export const metadata = {
	title: 'Redtide',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	//${jose.variable} font-jose ${kanit.variable} font-kanit
	return (
		<div>
			<Header />
			{children}
			{/* <Footer /> */}
		</div>
	);
}
